language: cpp
compiler:
- gcc
before_install:
- openssl aes-256-cbc
  -K $encrypted_74e7c0811ff1_key
  -iv $encrypted_74e7c0811ff1_iv
  -in travisci_rsa.enc
  -out travisci_rsa -d
- chmod 0600 travisci_rsa
- mv travisci_rsa ~/.ssh/id_rsa
- sudo apt-get install -y protobuf-compiler libprotobuf-dev
- sudo apt-get install -y libcrypto++-dev
- sudo apt-get --no-install-recommends install -y doxygen
- echo "HTML_TIMESTAMP = no" >> docs/Doxyfile
script:
- scons NUMCPUS=2
- VERBOSE=1 build/test/test --gtest_filter='-*TimingSensitive*'
- VERBOSE=1 build/test/test --gtest_filter='*TimingSensitive*' || true
- ./build/Examples/SmokeTest --mock
- scons check
- scons docs && ./scripts/publish-doxygen
